engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
    - 491dd5b768852a27a80385aa82cf7e58
    - 538d87ce2b9bc468129f55f4f3978e58
    - 3a467030ef89f45f0d86a03cb629fb75
    - 39cf272b046d1677fb4ee2b97afb4998
    - 2ad1dc6314661ff8bcf4fdaba7b13b5e
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/RescueException:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- benchmark/
- docs/
- gemfiles/
- spec/
